version: "3.7"

services:
  db:
    image: mysql:8.0
    container_name: exchange-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker-net-exchange
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    image: nginx
    container_name: exchange-web
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-net-exchange
    
  app:
    build: ./
    container_name: exchange-app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      - docker-net-exchange
    environment:
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      PHP_ENABLE_XDEBUG: 1
      TEST_RUNTIME_PATH: /tmp/runtime
      API_JWT_DOMAIN_CHECK: ${API_JWT_DOMAIN_CHECK}
      API_JWT_SECRET_KEY: ${API_JWT_SECRET_KEY}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN: ${DOMAIN}
      COOKIE_BACKEND_VALIDATION_KEY: ${COOKIE_BACKEND_VALIDATION_KEY}
      COOKIE_FRONTEND_VALIDATION_KEY: ${COOKIE_FRONTEND_VALIDATION_KEY}

networks:
  docker-net-exchange:
    driver: 'bridge'
volumes:
  db-data: